project_id = "wxiyjvtqgvbvcscbxxnq"

[functions.staff-auth]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-portal]
verify_jwt = false